name: Feature Test

on:
  - push
  - pull_request

jobs:
  build:
    name: Jekyll ${{ matrix.jekyll }} on Ruby ${{ matrix.ruby }}

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        ruby:
          - '2.7'
          - '2.6'
          - '2.5'
        jekyll:
          - '4.0'
          - '3.8'

    steps:
      - name: Checkout reposity
        uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Set up Dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -yqq install graphviz \
              default-jre-headless \
              npm \
              python3 \
              python3-pip \
              python3-setuptools

          # Dependencies of mermaid
          sudo apt-get -yqq install libatk1.0-0 \
              libatk-bridge2.0-0 \
              libgtk-3-0 \
              libx11-xcb1 \
              libxcomposite1 \
              libxrandr2 \
              libxss1
          npm config set prefix "$HOME/.npm"
          npm install -g mermaid.cli \
              nomnoml \
              state-machine-cat \
              vega-cli \
              vega-lite \
              wavedrom-cli

          # Dependencies of syntrax
          sudo apt-get -yqq install libpango1.0-dev \
              libpython3-dev \
              python3-cairo \
              python3-gi \
              python3-gi-cairo
          pip3 install blockdiag seqdiag actdiag nwdiag syntrax

      - name: Set up Jekyll ${{ matrix.jekyll }}
        run: |
          bundle install --jobs 4 --retry 3 --gemfile=gemfiles/${{ matrix.jekyll }}.gemfile

      - name: Set up PATH
        run: |
          export PATH="$HOME/.local/bin:$HOME/.npm/bin:$PATH"

      - name: Run Feature Test
        run: bundle exec rake test:features
